version: "3"

services:
  postgres_db:
    container_name: postgres_db
    build: ./db
    image: postgres
    environment:
      - POSTGRES_DB=pokedex
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
    networks:
      - backend

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
    networks:
      - backend

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    command: python app.py
    env_file:
      - ./server/.env
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
      - pgadmin
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
